-- run "psql postgres"
-- CREATE DATABASE profiles; 
-- run \c to change to heroku database
-- psql profiles -a -f users.psql  


DROP TABLE IF EXISTS users;

CREATE TABLE users(
    ID SERIAL PRIMARY KEY,
    username TEXT,
    pass TEXT
);

INSERT INTO users (username, pass) 
VALUES ('diane', 'p0ma');



------------------------------------------------------------------------
    

SELECT * 
FROM users


